
on:
  pull_request:
    branches: -master

jobs:
     runs-on: ubuntu-latest
     steps:
    -uses: actions/checkout@v2
    run: echo "running tests"
     shesll: bash
    displayName: 'Run continuous integration tests'