
on:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest

  steps:
    -uses: actions/checkout@v2
    -script: mvn clean test
    displayName: 'Run continuous integration tests'