name: Hello workflow
on:
  pull_request:
    branches: -master
    workflow_dispatch:

jobs:
  CICD:
     runs-on: ubuntu-latest
     steps:
    -uses: actions/checkout@v2
     -name: Automation
    run: echo "running tests"
     shell: bash
